# Generated by Django 4.0.2 on 2022-02-28 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('patente', models.CharField(choices=[('S2', 'Soldado de 2ª Classe'), ('S1', 'Soldado de 1ª Classe'), ('CB', 'Cabo'), ('3S', '3º Sargento'), ('2S', '2º Sargento'), ('1S', '1º Sargento'), ('SO', 'Sub-Oficial'), ('AP', 'Aspirante'), ('2T', '2º Tenente'), ('1T', '1º Tenente'), ('CP', 'Capitão'), ('MJ', 'Major'), ('TC', 'Tenente-Coronel'), ('CL', 'Coronel'), ('BR', 'Brigadeiro'), ('MB', 'Major-Brigadeiro'), ('TB', 'Tenente-Brigadeiro'), ('CV', 'Civil')], max_length=2)),
                ('email', models.EmailField(max_length=50)),
                ('contato', models.CharField(max_length=11)),
                ('projeto', models.CharField(choices=[('FABDOC', 'FABDOC'), ('SPCOA', 'SPCOA'), ('SAGEM', 'SAGEM'), ('C2/CENTRAL', 'C2/CENTRAL'), ('C2/DEA2', 'C2/DEA2'), ('C2/HERCULES 2', 'C2/HERCULES 2'), ('IFFM4BR', 'IFFM4BR'), ('SIMULADOR T27', 'SIMULADOR T27'), ('A29 RV', 'A29 RV')], max_length=13)),
                ('feedback', models.TextField(max_length=500)),
            ],
        ),
    ]
